<div id="select-staff" data-bind="scope: 'staffs'">
    <select style="width:45%; float:left; margin-right:5%" data-bind="options: staffs,
                       optionsText: 'label',
                       optionsValue: 'value',
                       optionsCaption: 'Choose staff name...', value: selectedItem" name="dropdown">
    </select>
    <span id="show">&nbsp;</span>
</div>
<div style="margin-top:50px" data-bind="scope: 'staffs'">
    <button id="add" data-bind="click: showForm">Add</button>
</div>
<div data-bind="scope: 'staffs'" id="form" style="margin-top:50px; display:none">
    <label style="display: inline-block;width: 10%;">Name : </label><input value='' id='name'
        data-bind="value: input_name"> <br>
    <label style="display: inline-block;width: 10%;">Age : </label><input value='' id='age'
        data-bind="value: input_age"> <br>
    <label style="display: inline-block;width: 10%;">Job : </label><input value='' id='job'
        data-bind="value: input_job">
    <div style="margin-top:50px">
        <button id="save" data-bind="click: saveForm">Save</button>
    </div>
</div>

<script type="text/x-magento-init">
{
    "#select-staff": {
        "Magento_Ui/js/core/app": {
           "components": {
                "staffs": {
                    "component": "Htc_Knockout/js/knockout",
                    "config": <?= $block->getConfigData() ?>
                }
            }
        }
    }
}
</script>