<div class="row">
    <div class="column">
        <div class="circle1">SPECIAL OFFERS</div>
    </div>
    <div class="column">
    </div>
    <div class="column">
        <div class="circle2">NEW</div>
    </div>
</div>
<div class="row">
    <div class="column">
        <div class="name">
            <h3>SERA Stuffed Green Olives Paprika 350gr</h3>
            <button class="button2">All offers</button>
        </div>
        <div class="image">
            <img src="<?php echo $this->getViewFileUrl('Htc_Bt4::images/a2.png'); ?>">
        </div>
    </div>
    <div class="column">
    </div>
    <div class="column">
        <div class="name">
            <h3>MELIS Pickled Gherkins 2.650m1</h3>
            <button class="button2">All new items</button>
        </div>
        <div class="image">
            <img src="<?php echo $this->getViewFileUrl('Htc_Bt4::images/a1.png'); ?>">
        </div>
    </div>
</div>
<div class="row2">
    <div class="column">
        <p>&#x2713;&ensp; Family business</p>
    </div>
    <div class="column">
        <p>&#x2713;&ensp; More than 2500 foreign products</p>
    </div>
</div>
<div class="row3">
    <div class="column" style="background-color:#5EA2F3">
        <h2><b>Chilled products</b></h2>
        <button class="button">View all products</button>
    </div>
    <div class="column" style="background-color:#949D5E">
        <h2><b>Bio products</b></h2>
        <button class="button">View all products</button>
    </div>
    <div class="column" style="background-color:#B31925">
        <h2><b>Drinks</b></h2>
        <button class="button">View all products</button>
    </div>
</div>
<div class="row4">
    <div class="column" style="background-color:#F5A41D">
        <h2><b>Groceries</b></h2>
        <button class="button">View all products</button>
    </div>
    <div class="column" style="background-color:#FD6905">
        <h2><b>Non-food</b></h2>
        <button class="button">View all products</button>
    </div>
</div>